### ISSUE TITLE
Put wheels on pypi?

### ISSUE THREAD

**Issue by asottile** [pytest-dev/pluggy#111]
There's wheels for 0.3.0, 0.3.1, and 0.4.0 but not for any later versions.

**Comment by tgoodlet** [comment]
@nicoddemus @RonnyPfannschmidt @hpk42 is this something we want to continue distributing?

**Comment by anthrotype** [comment]
why not?

**Comment by nicoddemus** [comment]
@tgoodlet I don't see why not... do you see a problem with it @tgoodlet?

**Comment by tgoodlet** [comment]
No definitely not I just hadn't ever heard talk of it since I've joined.
I'll take a look.

**Comment by nicoddemus** [comment]
We could also consider making deployment automatic from Travis, for example how [pytest-xdist](https://github.com/pytest-dev/pytest-xdist/blob/4dc86a1dad8e1924064db32d5b9ea49f2e33c2e1/.travis.yml#L50-L59) does it.

**Comment by tgoodlet** [comment]
This ties in with #127. I'll try to get this set up today.

**Comment by RonnyPfannschmidt** [comment]
we should always in any case publish wheels

**Comment by asottile** [comment]
Especially when pluggy is listed on https://pythonwheels.com/ :)

**Comment by asottile** [comment]
It's been about four months, the manual operation takes ~15 seconds -- are we holding out for automation here? (might be a bit over-engineering-y for something that releases so infrequently)

**Comment by tgoodlet** [comment]
@asottile see #127 everything should be up except for `0.5.0`.

As per my comment there unfortunately I erroneously reverted the universal wheel upload for `0.6.0` but there are independent python wheels instead. If you know a way to work around that limitation/feature of `pypi` do let me know and I'll try to fix it (just use a different file name?). I also don't know why `pluggy` still isn't showing a check mark on https://pythonwheels.com/?

This should all be automated for the next release as per #131.

**Comment by asottile** [comment]
Looks good now!

![](https://i.fluffy.cc/DsPX823Bl7rJFg5GGkh5CZhmzG1VR8Mg.png)

I'm not sure there's much that can be done after the fact, but the separate py2 / py3 wheels aren't really a problem (as long as they're both there).  Looks like it'll be fine [next release](https://github.com/pytest-dev/pluggy/blob/e57c82a7c60c10a6945ad9b0cfbf129595f15c16/setup.cfg#L1-L2)

Thanks again!
