### ISSUE TITLE
release universal wheels

### ISSUE THREAD

**Issue by graingert** [pytest-dev/pluggy#127]
```sh
git checkout 0.6.0
python3 -m pip install -U pip setuptools wheel
python3 setup.py bdist_wheel upload
```

**Comment by tgoodlet** [comment]
@graingert thanks for the issue!
I'll try to ship these out this aft :+1:

**Comment by RonnyPfannschmidt** [comment]
can we automate this so every release gets sdist + wheels

**Comment by graingert** [comment]
I'm pretty sure you can file a ticket to restore a deleted file. Replacing
it is the only no no

**Comment by tgoodlet** [comment]
@graingert cool do you know where to do / request that?

**Comment by graingert** [comment]
@tgoodlet you just `twine upload ` the original wheel
