### ISSUE TITLE
Start recommending and using pipenv?

### ISSUE THREAD

**Issue by tgoodlet** [pytest-dev/pluggy#132]
[`pipenv`](https://docs.pipenv.org/) is where [pypa is headed](https://packaging.python.org/tutorials/managing-dependencies/#managing-dependencies) and I've personally used it in a project with great success.

**Comment by RonnyPfannschmidt** [comment]
given the current usage of tox and the lack of deps, to me it seems pipenv is simply not needed for pluggy

**Comment by tgoodlet** [comment]
Preemptive excitement...

**Comment by RonnyPfannschmidt** [comment]
also i just tried pipenv, its a big fat broken wtf thing

**Comment by tgoodlet** [comment]
@RonnyPfannschmidt oh weird I had a pretty good experience, shrug.
