### ISSUE TITLE
Wheels for 0.6.0 release changed on pypi

### ISSUE THREAD

**Issue by EnTeQuAk** [pytest-dev/pluggy#134]
Currently all our CI tests are failing because on 2018-04-15 the wheels on pypi changed for version 0.6.0 -> https://pypi.python.org/pypi/pluggy

SHA256 of the old wheel: 7f8ae7f5bdf75671a718d2daf0a64b7885f74510bcd98b1a0bb420eb9a9d0cff
SHA256 of the new wheel: d345c8fe681115900d6da8d048ba67c25df42973bda370783cd58826442dcd7c

The tar didn't change.

I don't see any changes between their `__init__.py` file and `callers.py` and assume that maybe now you changed some ignore files so that now less files are packaged (e.g, there's no `LICENSE`, no `testing` etc in the wheel)

Can you confirm that change? Especially with no changes in this repository this is concerning and changes to existing releases really should never happen.

**Comment by tgoodlet** [comment]
@EnTeQuAk yes that was myself this morning. It was to address #111 and #127.
I can confirm this was indeed us and hopefully it didn't cause you too much pain.

**Comment by EnTeQuAk** [comment]
> @EnTeQuAk yes that was myself this morning. It was to address #111 and #127.
I can confirm this was indeed us and hopefully it didn't cause you too much pain.

Thanks! That helps to sort this out next to just verifying the code manually. I know it's probably obvious but I'd prefer if there are any changes needed in the released packages it's usually better to just issue a dot-release.

**Comment by tgoodlet** [comment]
@EnTeQuAk no problem!

This was actually my bad as I erroneously deleted a wheel release file without knowing the consequences when playing with warehouse...

We're planning to automate this in the future as per #131 so this should never happen again.
For the record the py3 wheel is SHA256: `d345c8fe681115900d6da8d048ba67c25df42973bda370783cd58826442dcd7c` and the py2 wheel is `7f8ae7f5bdf75671a718d2daf0a64b7885f74510bcd98b1a0bb420eb9a9d0cff`.

**Comment by graingert** [comment]
@EnTeQuAk do you happen to have a copy of the file with the hash 7f8ae7f5bdf75671a718d2daf0a64b7885f74510bcd98b1a0bb420eb9a9d0cff ?

**Comment by stephsamson** [comment]
I am receiving a new hash for `pluggy==0.6.0`:

```
e160a7fcf25762bb60efc7e171d4497ff1d8d2d75a3d0df7a21b76821ecbf5c5
```

**Comment by graingert** [comment]
@stephsamson are you sure this wasn't already reported?

**Comment by stephsamson** [comment]
@graingert Honestly, I am not certain -- I could be very wrong but since a week ago, the hash has changed from [@tgoodlet's comment](https://github.com/pytest-dev/pluggy/issues/134#issuecomment-381487368)  a few days ago. Check [PyPi for the latest hash.](https://pypi.org/project/pluggy/#files)
