### ISSUE TITLE
high level overview

### ISSUE THREAD

**Issue by techtonik** [pytest-dev/pluggy#14]
The description "as used by py.test" is not very helpful. To be able to compare with other known plugin systems like Trac, SCons , Roundup or Spyder I need to answer the questions:
1. how plugin discovery is made
2. how plugin loading happens
3. when plugin initialization occurs

**Comment by RonnyPfannschmidt** [comment]
1/2) both setuptools entrypoints and custom loading are upported
3) all added plugins are constructed instances or modules,
   the typical method to do global initialization is to create a historic configuration hook that
  gets called on each added plugin (like pytest_configure)

**Comment by techtonik** [comment]
> 1/2) both setuptools entrypoints and custom loading are upported

This explanation is no better than "as used by py.test". =)

3) what is "global" initialization and what is "normal" initialiation in this case?

**Comment by RonnyPfannschmidt** [comment]
there is no "normal"

you'd just have a hook thats called on all plugins that get registered in all variants it was called with

there is a reason why i strongly referred to pytest internal usages,
we are rather short on time atm
n

**Comment by nicoddemus** [comment]
@techtonik one of the milestones for a pluggy `1.0` release is complete docs, which as @RonnyPfannschmidt said probably won't be available in the short term.

We should use this issue to remember ourselves of the need for better documentation on pluggy.

**Comment by techtonik** [comment]
I see.

> you'd just have a hook thats called on all plugins that get registered in all variants it was called with

Before a hook is called on a plugin, you need to find and import that plugin. Is that "hook" is just a function that should be implemented by a module as a part of plugin interface?

**Comment by RonnyPfannschmidt** [comment]
Yes, the pytest_configure hook in pytest is one such example

**Comment by techtonik** [comment]
Ok. hooks == plugin api == plugin callbacks. Thanks for the explanations.

**Comment by Nick0001** [comment]
Hello, I'm in the process of implementing plugins using pluggy in our own application. Is there a more elaborate description of how to use pluggy? When can pluggy 1.0 be expected? When can pytest 3 be expected?

**Comment by nicoddemus** [comment]
> When can pluggy 1.0 be expected?

Not sure, @hpk42 could comment on that.

> When can pytest 3 be expected?

I would say sometime after our sprint, which will end on June 25th.

**Comment by tgoodlet** [comment]
@nicoddemus @RonnyPfannschmidt @hpk42 I'd be willing to take a stab at this.

I've now used `pluggy` in [another small project](https://github.com/SIPp/pysipp) and also have pretty decent experience with `pytest` at this point. I also have combed the `pluggy` source code multiple times and am pretty sure I have a decent grasp of the internals. I've been trying to use `pluggy` as a means to learn `pytest` from the *bottom up* for some time now but I need some deadlines to move it along.

I'd be willing to submit a PR for sphinx docs within the next few weeks. My only request is that eventually this project is moved to the `pytest-dev` org and maintained more prominently there.

**Comment by RonnyPfannschmidt** [comment]
I did send @hpk42 a mail about that
He will react after returning from his current travel

**Comment by nicoddemus** [comment]
My personal opinion is that I certainly would love to have some docs for the project! I would also like to move it to `pytest-dev`, but let's see what @hpk42 has to say about that.

**Comment by tgoodlet** [comment]
@RonnyPfannschmidt @nicoddemus well it looks like we got our wish!

Are you guys cool with sphinx + the alabaster theme to start?

**Comment by nicoddemus** [comment]
Hey @tgoodlet! :grin: 

I think Sphinx is fine, but if you don't mind I would rather publish to readthedocs with the default readthedocs theme. What do you think?

**Comment by tgoodlet** [comment]
@nicoddemus sure works for me. I'll get something cobbled together in the next week or so and link you guys.

**Comment by nicoddemus** [comment]
Nice, sounds good! Thanks a lot for your interest, it is really appreciated by the team! :+1: 

Btw, already created the project on [readthedocs](https://readthedocs.org/projects/pluggy/). :grin:

**Comment by hpk42** [comment]
I'd be very happy with a sphinx project even by just having nice API online documentation.   @tgoodlet if you go for this we could eventually go for pluggy-1.0 i think :+1:

**Comment by tgoodlet** [comment]
@hpk42 yeah I know I kinda dropped the ball on this...been busy.

It's Pycon Canada this weekend in Toronto so I'll try to jam something out at the very least during the sprints Mon-Tues.

**Comment by RonnyPfannschmidt** [comment]
actually, let me just do a quick and dirty initial setup with only api docs

**Comment by tgoodlet** [comment]
@RonnyPfannschmidt so are you going to push up just a sphinx autodoc draft?

I'm a fan of you getting the rtd build up and running since I don't have access currently ;)
