### ISSUE TITLE
Someone should pin pluggy on the pytest-dev board!

### ISSUE THREAD

**Issue by tgoodlet** [pytest-dev/pluggy#146]
I noticed the only 2 projects [pinned thus far](https://github.com/pytest-dev) are `pytest` and `py`.
`pluggy` should be up there too as it's pretty fundamental to the whole ecosystem and is picking up some stars and contributions :)

I'd do it myself but don't have the permissions :(

Ping @RonnyPfannschmidt @nicoddemus @hpk42

**Comment by nicoddemus** [comment]
Done! 

I also invited you to the Core team, as I'm sure the other members all agree given all your contributions to `pluggy`! 😁
