### ISSUE TITLE
Keep CHANGELOG updated with PRs?

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pluggy#148]
I suggest we keep the CHANGELOG updated as we merge PRs (even so far as making it part of the PR to update the CHANGELOG). Benefits:

* No need to dig around to see which issues have been addressed since the last release, making the job of people making releases (mainly @tgoodlet lately) a lot easier.

* Clear overview of what is about to be released at a glance.

We could adopt `towncrier` like pytest does, but given that `pluggy` does not have the same PR activity as pytest this is not necessary IMO.

**Comment by tgoodlet** [comment]
@nicoddemus I think we have #66 and #73 already to get this in yeah?

**Comment by nicoddemus** [comment]
Definitely, my bad! 😁 

Closing as duplicate of #66.
