### ISSUE TITLE
How do wrappers force all results up to the first error?

### ISSUE THREAD

**Issue by tgoodlet** [pytest-dev/pluggy#149]
I was thinking about this as I was writing up #142 and realized there seems to be no *public* API way to accomplish this. That is, how does one use a wrapper to stuff all the results up to when the first `hookimpl` fails? Currently `_Result.get_result()` will raise and `_Result.result` is being deprecated so the only way I can think of currently is using the internal `_result` instance var:

```python
@hookimpl(hookwrapper=True):
    outcome = yield
    if test_for_exc_to_swallow(outcome.excinfo):
        outcome.force_result(outcome._result)
        oucome._excinfo = None
```

Maybe this is just a naughty use case and we shouldn't be concerned?

**Comment by RonnyPfannschmidt** [comment]
unless there is a known real-world use-case i'd wait for someone to come up with a actual one

**Comment by tgoodlet** [comment]
Cool just thought I'd write up the thought while I had it.
