### ISSUE TITLE
Refer to changelog in readme or docs

### ISSUE THREAD

**Issue by fschulze** [pytest-dev/pluggy#165]
The changelog isn't linked or copied into the docs at the moment.

Personally I like it attached to the readme in the ``long_description``, so one sees it on pypi.org.

They should definitely be included in the docs somehow.

If there is consensus on where it should go then I can make a PR.

**Comment by nicoddemus** [comment]
I'm fine either way. Feel free to open a PR with you preference @fschulze! 👍

**Comment by tgoodlet** [comment]
@fschulze same. Whatever you think is best is fine by me!
