### ISSUE TITLE
TOC side panel dissapeared in docs

### ISSUE THREAD

**Issue by tgoodlet** [pytest-dev/pluggy#171]
[It's gone!](https://pluggy.readthedocs.io/en/latest/) :disappointed: 
Is it a theme change?

**Comment by obestwalter** [comment]
Interesting - tox also uses alabaster 0.7.11 theme and is still looking o.k., so I guess it has to do with something specific to the pluggy docs.

**Comment by tgoodlet** [comment]
@gyermolenko we used to see an index of all the (sub)sections from headings in `index.rst` iirc?
So I guess we're missing whatever `tox` has that we don't because they have what it used to be [on the left side panel](https://tox.readthedocs.io/en/latest/).

**Comment by tgoodlet** [comment]
Think I found [what we're missing](https://github.com/tox-dev/tox/blob/master/docs/conf.py#L79).

**Comment by tgoodlet** [comment]
pfff well [that didn't work](https://pluggy.readthedocs.io/en/latest/)...

**Comment by tgoodlet** [comment]
Tried to base it off what the [`tox` team does](https://github.com/tox-dev/tox/blob/master/docs/conf.py#L67) but I ain't seein how they got the good results I'm missing.

**Comment by tgoodlet** [comment]
Woa ok what the heck?

https://pluggy.readthedocs.io/en/latest/index.html shows what I want but,
https://pluggy.readthedocs.io/en/latest/ is not?

**Comment by tgoodlet** [comment]
Yeah it was my stupid browser cache...
