### ISSUE TITLE
Introduce attrs?

### ISSUE THREAD

**Issue by goodboy** [pytest-dev/pluggy#176]
I was thinking about introducing [`attrs`](https://github.com/python-attrs/attrs) since I've heard @RonnyPfannschmidt is a fan and I think it would result in a pretty nice cleanup.

**Comment by goodboy** [comment]
I don't think we need this in `1.0` personally though probably somewhere in the `1.0` releases.

**Comment by RonnyPfannschmidt** [comment]
I think we need a cython component as well

**Comment by goodboy** [comment]
@RonnyPfannschmidt I'm pretty sure I already wrote one? It was like 2 or 3 years ago :laughing:

**Comment by RonnyPfannschmidt** [comment]
I don't recall why that was stalled

**Comment by goodboy** [comment]
@RonnyPfannschmidt i made #104 to continue discussion but I can't really either?

**Comment by bluetech** [comment]
attrs is great and I use it myself, but my opinion is that the benefits of attrs are not sufficient in this case for imposing the dependency on users of `pluggy`. It also has a non-negligible startup-time overhead compared to plain code in my experience.

**Comment by goodboy** [comment]
@bluetech I was also going to say with the new [`dataclasses`](https://docs.python.org/3.8/library/dataclasses.html) and type annotations stuff I'm not sure we'll need the extras `attrs` offers outside of what's already included in the stdlib.

**Comment by RonnyPfannschmidt** [comment]
Let's avoid attrs here for its cost
