### ISSUE TITLE
Support PyPy3?

### ISSUE THREAD

**Issue by hsoft** [pytest-dev/pluggy#187]
I see that pluggy supports PyPy, but does it support PyPy3? In Gentoo, [we have a failing test](https://bugs.gentoo.org/648672) when running tests under PyPy3.

**Comment by tgoodlet** [comment]
Excellent question @hsoft and we 100% want to support `pypy3`.

We [don't seem to test in CI currently](https://github.com/pytest-dev/pluggy/blob/master/.travis.yml#L23), nor [with `tox`](https://github.com/pytest-dev/pluggy/blob/master/tox.ini#L2).

This is definitely needed!
Looks like it's pretty simple to get going according to the [TravisCI docs](https://docs.travis-ci.com/user/languages/python/#pypy-support).
