### ISSUE TITLE
Marking hookspec as requiring at least one implementation

### ISSUE THREAD

**Issue by MrGreenTea** [pytest-dev/pluggy#20]
For some hooks it would be great if I could make an implementation for it mandatory, so that it doesn't just do nothing but raises an Error when called.
What are your thoughts on that?

**Comment by nicoddemus** [comment]
I don't think there's support for that currently, but one workaround might for your plugin to implement the hook and return some sentinal object. When you call the hook implementation, you then might check if the call returned only `[sentinel]` which means only your call was implemented and treat that accordingly.

**Comment by MrGreenTea** [comment]
I implemented that functionality, but am unsure how to name the parameter.
`requireimplementation=True` is very long and not as readable as I would like, `require_implementation=True` is inconsistent with the other parameter `firstresult`.
I named it `requireimpl` for now, because of `HookImplMarker` and it often being assigned to `hookimpl`.

What do you/others think?

**Comment by nicoddemus** [comment]
How about `required=True`?

**Comment by hoefling** [comment]
@nicoddemus: 

> When you call the hook implementation, you then might check if the call returned only [sentinel] which means only your call was implemented and treat that accordingly.

This means that it's not possible to validate plugin availability without their implicit execution?

**Comment by MrGreenTea** [comment]
`required=True` sounds good, but I feel is not telling enough what exactly is required.

@hoefling Do you mean hook implementations? There is a `has_plugin` method for checking plugin availability.

**Comment by nicoddemus** [comment]
IMHO:

```python
@hookspec(required=True)
def my_hook():
```

Is clear enough, but that's just me. `requireimpl` sounds fine as well, although I like my suggestion better. :grin:

**Comment by MrGreenTea** [comment]
I would love to hear another opinion on this, though I agree with you that `required` looks nicer :)

**Comment by hoefling** [comment]
@MrGreenTea:
> Do you mean hook implementations?
Sure, my bad.

**Comment by hpk42** [comment]
I am with hoefling on that ``required=True`` does not convey much meaning.  

Moreover, i am skeptical of putting this into the hookspec.  I'd rather like to have another runtime-API like ``my_hook.has_implementations()`` returning True or False.  In several projects using pluggy i've never had the need for asserting that a hook must have implementations FWIW.

**Comment by MrGreenTea** [comment]
I believe having it in the actual hook definition makes it easier to see what hooks require an implementation. Having to find the places where the hook is called and checking if their is a check for `my_hook.has_implementation()` sounds unnecessary when developing plugins. It also adheres to the  principle of EAFP.


We plan on using pluggy to allow easy interchangability of parts of the system, also for some "core functionality" of the whole system. That's where I believe an explicit error will help in development and testing.

**Comment by RonnyPfannschmidt** [comment]
why is it a problem to begin with if certain hooks have no implementation at all?

@MrGreenTea do you have a minimal example that illustrates this, both @hpk42 and me have a very different perspective on the issue/usage and may be completely missing your point without a painfully oblivious illustration

**Comment by hpk42** [comment]
I am closing this as i don't see enough rationale yet for adding something to hookspec.  I'd like to keep pluggy minimal especially wrt to hookspec.  I hold that something like ``assert hook.has_implementations()`` would be sufficient and simpler to understand directly at the calling site of the hook.  @MrGreenTea feel free to add a PR along those lines and thanks for your efforts so far!
