### ISSUE TITLE
Use standard library importlib.metadata on Python 3.8

### ISSUE THREAD

**Issue by hroncok** [pytest-dev/pluggy#222]
Once we update Python in Fedora to 3.8, we'd like our pluggy package to use `importlib.metadata` from the standard library. Would you accept a PR that makes the dependency on external `importlib_metadata` optional (only use it on Python < 3.8)?

**Comment by nicoddemus** [comment]
I defer the final decision to @asottile, but it seems reasonable to me! 👍

**Comment by asottile** [comment]
👍

**Comment by matejcik** [comment]
Please release a fix for this issue. This now breaks pluggy and pytest on Python 3.8 with `importlib_metadata` 0.21 -- see https://gitlab.com/python-devs/importlib_metadata/issues/86

**Comment by nicoddemus** [comment]
0.13 should be released soon: https://github.com/pytest-dev/pluggy/pull/234
