### ISSUE TITLE
Version 0.6.0 reuploaded ?

### ISSUE THREAD

**Issue by vin01** [pytest-dev/pluggy#228]
It looks like hashes for the `0.6.0` wheel have been updated however I still see the old date at https://pypi.org/project/pluggy/0.6.0/#modal-close (15 Apr 2018)

New hash (py2): `d345c8fe681115900d6da8d048ba67c25df42973bda370783cd58826442dcd7c`

Old hash: `7f8ae7f5bdf75671a718d2daf0a64b7885f74510bcd98b1a0bb420eb9a9d0cff`

Is this expected?

I just noticed it as it led to failure of one of my recent PR's tests.

Successful tests with same pluggy version in requirements file 28 days ago: https://travis-ci.org/linkedin/qark/jobs/557908230

Failure today: https://travis-ci.org/linkedin/qark/jobs/569709745

Thanks!

**Comment by nicoddemus** [comment]
Yes, unfortunately this was done by mistake on our side (https://github.com/pytest-dev/pluggy/issues/135). We hope it never happens again.

Closing now, feel free to follow with further questions. 👍

**Comment by vin01** [comment]
Thanks @nicoddemus not to pick on you but just to confirm as I did notice the linked issue before reporting, the linked issue is from Apr 2018, however this hash change I mentioned is more recent, so did you refer to the earlier issue just to share that the reason is same as the earlier hash change?

**Comment by nicoddemus** [comment]
Oh sorry about that.

Weird, no, I'm not aware of this happening again recently. @goodboy do you have any inputs here?

**Comment by vin01** [comment]
Ah, digging further in previous successful build: https://travis-ci.org/linkedin/qark/jobs/557908230#L479

```
Requirement already satisfied: pluggy==0.6.0 in /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages (from -r requirements-test.txt (line 79))
```

So it might indeed be the same issue. I am going to update the hash to `d345c8fe681115900d6da8d048ba67c25df42973bda370783cd58826442dcd7c`

Thanks @nicoddemus
