### ISSUE TITLE
Indirect dependency on Python 3 only library

### ISSUE THREAD

**Issue by hackebrot** [pytest-dev/pluggy#231]
Hi friends! 👋 

The cookiecutter builds are currently [failing for Python 2.7](https://ci.appveyor.com/project/cookiecutter/cookiecutter/branch/master/job/ec787v2rawykero1) environments due to an indirect dependency on a Python 3 only library in pluggy: [more_itertools](https://pypi.org/project/more-itertools)

Please see the discussion over at https://github.com/tox-dev/tox/issues/1406 for more information.

**Comment by hackebrot** [comment]
Hi @nicoddemus! 👋 

Upgrading virtualenv for our windows CI solved the problem for us.

I wonder if we need to document this for users of pytest 4.6... 🤔

**Comment by bluetech** [comment]
I think this issue can be closed, especially now that pluggy is dropping Python 2 support :)

**Comment by goodboy** [comment]
@bluetech indeed closing and if anyone wants to re-discuss for some reason later, so be it.
