### ISSUE TITLE
documentation old

### ISSUE THREAD

**Issue by gaborbernat** [pytest-dev/pluggy#243]
The readthedocs documentation says it's for version 0.8.x but latest is 0.13.1 https://pluggy.readthedocs.io/en/latest/

**Comment by blueyed** [comment]
This can be best seen from the changelog: https://pluggy.readthedocs.io/en/latest/changelog.html
Are the RTD builds failing?  Can somebody with access check the logs?

**Comment by RonnyPfannschmidt** [comment]
based on https://readthedocs.org/projects/pluggy/builds/ - it hasnt build in 10 months, i beleive its based on a required  reconf beginning this year, i'll get prerms

**Comment by RonnyPfannschmidt** [comment]
i re-synced the webooks and started the builds, i'll leave this one open until after the next merge to validate

**Comment by asottile** [comment]
looks fixed -- closing!
