### ISSUE TITLE
Can't pypi-install pluggy - PYPI returned unsafe url: ''

### ISSUE THREAD

**Issue by arthurlogilab** [pytest-dev/pluggy#26]
Trying to pypi-install (wrapper that generates a debian package from a pip install) I get the following error: 

```
# pypi-install --verbose 5 pluggy
downloading to /tmp/tmpoqv1mk
querying PyPI (https://pypi.python.org/pypi) for package name "pluggy"
found default release: 0.4.0
Traceback (most recent call last):
  File "/usr/bin/pypi-install", line 67, in <module>
    main()
  File "/usr/bin/pypi-install", line 48, in main
    allow_unsafe_download=options.allow_unsafe_download)
  File "/usr/lib/python2.7/dist-packages/stdeb/downloader.py", line 95, in get_source_tarball
    raise ValueError('PYPI returned unsafe url: %r' % download_url)
ValueError: PYPI returned unsafe url: ''
```

Is there something missing in setup.py ? in the description on pypi ?

**Comment by nicoddemus** [comment]
I just tried and it works for me.

Which pip version are you using?

**Comment by arthurlogilab** [comment]
Suprisingly enough python-pip is not required for pypi-install to work. 

the function that gets the download_url is here : https://github.com/astraw/stdeb/blob/master/stdeb/downloader.py#L20-L77

**Comment by RonnyPfannschmidt** [comment]
this seems to be a bug in stdeb

**Comment by nicoddemus** [comment]
Should we close this then, @arthurlogilab?
