### ISSUE TITLE
old installed importlib_metadata triggers issues on python 3.8

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pluggy#278]
ref https://github.com/pytest-dev/pytest/issues/7371

if the python version is recent enough i believe its a good idea to ensure the python api itself is used

**Comment by bluetech** [comment]
Should close this per https://github.com/pytest-dev/pytest/issues/7371#issuecomment-644149987

**Comment by RonnyPfannschmidt** [comment]
yes, thanks for taking a deeper look before i had a chance
