### ISSUE TITLE
Deeper inspection of hookspec for implementation

### ISSUE THREAD

**Issue by felixgao** [pytest-dev/pluggy#281]
Hi, I looked at the documentation and it seems to be that for each hookspec we should have a set of implementations that we want to run by all the plugins.  What my use case is something that might requires a deeper inspection of the spec. ex.

```
import panda as pd
from pluggy import HookspecMarker, HookimplMarker, PluginManager

spec = HookspecMarker("pluggy_df")
impl = HookimplMarker("pluggy_df")


class HookSpec:
    @spec
    def transform(self, df:pd.DataFrame, config:Config):
        pass

class HookImpl1:
    @impl
    def transform(self, df, config):
        return df[config.cols]

class HookImpl2:
    @impl
    def transform(self, df, config):
        return df.filter(**config.filter.conds)

pm = PluginManager("pluggy_df")
pm.add_hookspecs(HookSpec)
pm.register(HookImpl1())
pm.register(HookImpl2())
pm.hook.transform(df, config)
```

What I want to customize is when the dataframe have a certain schema then run the corresponding implementation.

**Comment by bluetech** [comment]
> when the dataframe have a certain schema then run the corresponding implementation

I am not super familiar with pandas; can you explain a bit more what you mean by this?

**Comment by RonnyPfannschmidt** [comment]
Conditions are supposed to happen in hooks, pluggy just runs all of them

**Comment by RonnyPfannschmidt** [comment]
closing as out of scope for pluggy (conditional hooks)
