### ISSUE TITLE
Documentation mentions "new in version 0.13.2", but that version was still not released

### ISSUE THREAD

**Issue by dmateusp** [pytest-dev/pluggy#286]
Just wanted to flag that this PR assumed 0.13.2 would be released soon after (I imagine), to include the "specname" argument, so I was surprised trying to use `specname` finding out that there is not release that includes it yet

https://github.com/pytest-dev/pluggy/pull/252/files#diff-8d068e8797e88947c320f79e856c3e16a72b730124a8f9d7031e2c4680dfa534R284

**Comment by hoefling** [comment]
Use https://pluggy.readthedocs.io/en/stable/ instead of https://pluggy.readthedocs.io/en/latest/ which is what pluggy.readthedocs.io redirects to by default. IIRC RTD allows to configure that - maybe it's better to redirect to stable docs by default.

**Comment by nicoddemus** [comment]
Changed default to `stable`, thanks for bringing this to attention. 👍
