### ISSUE TITLE
[Feature request] Remote plugins

### ISSUE THREAD

**Issue by Eshaan7** [pytest-dev/pluggy#291]
Idea: Allow importing external/remote plugins via URLs.

Using https://github.com/operatorequals/httpimport package, it may be possible to _hook_ into remote python scripts/packages.

Example code (which won't work because of different `hookimpl`):

```python
import httpimport
import pluggy

pm = pluggy.PluginManager("myproject")

with httpimport.remote_repo(["remote_plugin"], "https://gist.github.com/Eshaan7/94e8ea35079395483006b85b94c75183"):
    from remote_plugin import PluginXYZ
    pm.register(PluginXYZ())
```

So maybe there is a way to integrate `httpimport` directly into pluggy to allow for such use cases.

**Comment by RonnyPfannschmidt** [comment]
Big nope this looks broken, unless it turns into a proper pep this is not something pluggy will natively do

Based on what I see right now i highly doubt that

**Comment by nicoddemus** [comment]
I agree, definitely out of scope for pluggy I think. Can easily be implemented in another project which depends on Pluggy though, possibly subclassing `PluginManager`.

Thanks for the suggestion however @Eshaan7.

Closing for now as "won't do".
