### ISSUE TITLE
Pluggy should install importlib_metadata for Python 3.7 or lower

### ISSUE THREAD

**Issue by liZe** [pytest-dev/pluggy#305]
importlib_metadata has been replaced by importlib.metadata in recent versions of Python (3.8+), but Pluggy still uses it for older versions of Python.

importlib_metadata should be included in the list of dependencies when Python 3.7 is used. If you agree, I can even open a PR to fix that.

**Comment by bluetech** [comment]
It is:

https://github.com/pytest-dev/pluggy/blob/2d01777a6f092cd90bceb7f58b3c128253bda008/setup.py#L43

**Comment by liZe** [comment]
Oh, that’s strange. I’ll try to find why it’s not automatically installed for me and come back soon.

**Comment by liZe** [comment]
We have probably had a problem with pipenv at some point, it seems to work now. Sorry for the noise.
