### ISSUE TITLE
Reorganize test classes into modules

### ISSUE THREAD

**Issue by tgoodlet** [pytest-dev/pluggy#32]
The `testing/test_pluggy.py` module is not only a bit long but also overwhelming.

I propose we break up the current organization of  as follows:
`TestPluginManager` -> `test_plugin_manager.py`
`TestAddMethodOrdering` -> `test_add_method_ordering.py`
`TestMultiCall` -> `test_multicall.py`
`TestHookRelay` -> `test_hook_relay.py`
`TestTracer` -> `test_tracer.py`

I personally think it just lends to a better immediate understanding of what tests are available/need to be written around each internal component of the `pluggy` architecture.

**Comment by hpk42** [comment]
i am fine with such a reorg PR -- please try to make history/blaming continue to work as much as possible.

**Comment by tgoodlet** [comment]
@hpk42 yeah I'm not sure I can maintain all that much in terms of blame. 
The new modules will be under my name..

Would you rather do it?

**Comment by RonnyPfannschmidt** [comment]
people can stil lblame from the old code in case of real interest - since source controll systems do not track code reorg in any repressentign way i think its fine to loose some

**Comment by hpk42** [comment]
@tgoodlet no worries.  Try to do all shifts in a single commit and make the commit message descriptive.  If neccessary people can figure it out as ronny says.  pity that git still does not have a "git cp" although it has a "git mv".

**Comment by hpk42** [comment]
@tgoodlet your avatar logo -- is that purposedly taken from this quite terrifying black mirror episode?

**Comment by nicoddemus** [comment]
I'm guessing that's the classic "troll face" :grin:

**Comment by tgoodlet** [comment]
@hpk42 yeah @nicoddemus is right although it's actually a bit of a story.

My buddy @vodik back in university found my email unlocked and stuck that pic as my avatar. I've been embracing it ever since. I wasn't much of an internet nerd back then so I had no idea where it came from at the time.
