### ISSUE TITLE
A small change about the add_hookspec method！

### ISSUE THREAD

**Issue by Northxw** [pytest-dev/pluggy#353]
Hello, since the for loop of add_hookspecs is to get the attribute project_name_spec of the class method or module decorated by the decorator class：
```
def add_hookspecs(self, module_or_class):
    """ add new hook specifications defined in the given ``module_or_class``.
    Functions are recognized if they have been decorated accordingly. """
    names = []
    for name in dir(module_or_class):
        spec_opts = self.parse_hookspec_opts(module_or_class, name)
        if spec_opts is not None:
            ...
```
Then for name in dir(module_or_class) can be changed to for name in dir(module_or_class)[::-1], can it be faster to find the new attributes of class methods？
Of course, in terms of time complexity, there seems to be no difference, please answer, thank you

**Comment by RonnyPfannschmidt** [comment]
It's not quite clear what you are trying to get at, we have to get all of them,
