### ISSUE TITLE
Does pluggy work with all package managers (setuptools, poetry, ...)?

### ISSUE THREAD

**Issue by cgebbe** [pytest-dev/pluggy#356]
Like the title says: Does pluggy work with all package managers (setuptools, poetry, ...)?

I'm asking because I just read that e.g. [poetry plugins only work _similarly_ to setuptools entry points](https://python-poetry.org/docs/pyproject/#plugins) and was therefore curious about this project.

**Comment by RonnyPfannschmidt** [comment]
Pluggy uses the entrypoint system that's supposed by all modern packaging tools

The api name is by now badly chosen as 10 years ago setuptools + pkg_resources was the only implementation
