### ISSUE TITLE
incorrect hookimpl signature inspection for decorated functions

### ISSUE THREAD

**Issue by eachimei** [pytest-dev/pluggy#358]
Please see details at: https://github.com/jaraco/keyring/pull/582#issuecomment-1200450421

Suggestion for `pluggy._hooks:varnames`: use `inspect.signature(func)` instead of `getfullargspec` since it has the ability to follow wrapper chains (and that's actually the default behavior): https://docs.python.org/3/library/inspect.html#inspect.signature

As can be seen in the mentioned comment above, the current code (pluggy 1.0.0) actually breaks/limits hook-implementations.

**Comment by RonnyPfannschmidt** [comment]
the "limit" was never intentional - its primarily a artifact of python 2 support, signature should be used these days

**Comment by eachimei** [comment]
[0001-proposed-fix-for-issue-358.patch.txt](https://github.com/pytest-dev/pluggy/files/9245181/0001-proposed-fix-for-issue-358.patch.txt)

Attached is a fix proposal (including a matching test) as a git-patch.

**Comment by RonnyPfannschmidt** [comment]
Why not open a pr?, this is absolutely horrible to work with from mobile, and it's still quite a pain if I get back to the computer

**Comment by eachimei** [comment]
I'd love to and I actually tried, but seems like I don't have permission to push a branch?

**Comment by nicoddemus** [comment]
@eachimei the way to contribute in GitHub in general is fork the repository, push your branch there, then open a PR. 👍

**Comment by eachimei** [comment]
I'd love to and I actually tried, but seems like I don't have permission to push a branch?
________________________________

**Comment by nicoddemus** [comment]
You need to create a fork, then push to your fork. From there you can open a PR to this repository.

**Comment by eachimei** [comment]
@nicoddemus 
> You need to create a fork, then push to your fork. From there you can open a PR to this repository.

Thank you, already done: PR approved but not merged yet: https://github.com/pytest-dev/pluggy/pull/359

**Comment by madkinsz** [comment]
@RonnyPfannschmidt looks like this can be closed as completed.

**Comment by RonnyPfannschmidt** [comment]
indeed, thanks
