### ISSUE TITLE
Please consider switching the build-system to flit_core to ease setuptools bootstrap

### ISSUE THREAD

**Issue by mgorny** [pytest-dev/pluggy#372]
Could you please consider switching the build system from setuptools to [flit_core](https://pypi.org/project/flit-core/)? This would help Linux distributions such as Gentoo avoid cyclic dependencies that cause bootstrapping unbundled setuptools a real pain. If you agree, I can submit a pull request doing the conversion.

The problem is that the most recent release of setuptools (66.0.0) started using platformdirs. platformdirs use the hatchling build backend which in turn requires this package. This creates a dependency cycle that we can't install setuptools before installing platformdirs, and we can't build platformdirs before all of hatchling's dependencies are installed, and we effectively end up needing setuptools to build them.

flit_core is a "no dependencies [except for tomli, on Python < 3.11]"  by design, so it makes bootstrapping packages much easier.

Unfortunately, I don't think it's possible to retain setuptools_scm-style logic then. While there's a flit_scm package providing equivalent functionality, it depends on setuptools_scm which invariably means a cyclic dependency with setuptools.

**Comment by bluetech** [comment]
@RonnyPfannschmidt since hatchling depends on pluggy, it does sounds like a good idea to avoid pluggy depending on hatchling. How do we expect distributions to package pluggy with a cyclic dependency like this?

**Comment by RonnyPfannschmidt** [comment]
@bluetech i am currently coordinating the details with the hatch author
