### ISSUE TITLE
Add a logo

### ISSUE THREAD

**Issue by tgoodlet** [pytest-dev/pluggy#40]
I think I found a good one using a plug symbol and we should be able to insert it using the built-in `sidebarlogo` in the `layout.html` [sphinx-template](http://www.sphinx-doc.org/en/1.5.1/templating.html).

**Comment by nicoddemus** [comment]
Can you show a preview somewhere? 😁

**Comment by nicoddemus** [comment]
(Only the logo, I mean)

**Comment by tgoodlet** [comment]
@nicoddemus I had this in mind :)
![plug](https://cloud.githubusercontent.com/assets/291685/22493312/727e8f0c-e7fd-11e6-9547-03fc927163f7.png)

**Comment by nicoddemus** [comment]
I like it. 👍 

If nobody manifests against it, I suggest to just add it to your PR. It is nice to have a logo initially and it is easy to change it later.

**Comment by hpk42** [comment]
i'd like it as initial logo modulo one change request: strip the left "wire", this also makes it a bit more quadratic which is useful.

**Comment by tgoodlet** [comment]
@hpk42 Ok i'll see what i can do.
I may make a separate PR to get this in if you guys don't mind?
