### ISSUE TITLE
RTD build keeps failing

### ISSUE THREAD

**Issue by tgoodlet** [pytest-dev/pluggy#41]
See the latest here: https://readthedocs.org/projects/pluggy/builds/

Looks like the culprit is:
```python
 File "conf.py", line 23, in <module>
    dist = pkg_resources.get_distribution('pluggy')
```
So I guess we aren't installing `pluggy` prior to docs building? That's a RTD config thing right?

I'd be happy to help with this but I don't have access :(

**Comment by nicoddemus** [comment]
Working now: http://pluggy.readthedocs.io/en/latest, all I had to do was to enable installing the project in a virtual env. 👍

**Comment by nicoddemus** [comment]
Hey @tgoodlet, I spoke with @hpk42 and we agreed to give you maintainer access to RTD in light of your excellent work. What's your username there?

Also, are you interested in becoming a maintainer of the repository as well?

**Comment by tgoodlet** [comment]
@nicoddemus that sounds great; my RTD user is the same as github `tgoodlet`.

Yes of course I'd love to help maintain the project!
I have to say `pluggy` has become a little like a pet to me :)

**Comment by nicoddemus** [comment]
@tgoodlet nice, welcome! 😉 

Added you as maintainer both here in GH and on RTD, let me know if there are any problems.

**Comment by tgoodlet** [comment]
@nicoddemus seems like both worked :+1: 
I look forward to helping get `pluggy` ready for the 2020 election ;)

**Comment by nicoddemus** [comment]
Heh! 👍 

Cheers 🍻
