### ISSUE TITLE
Patterns to enable and disable plugins?

### ISSUE THREAD

**Issue by simonw** [pytest-dev/pluggy#422]
I use Pluggy extensively for my [Datasette](https://datasette.io) and [LLM](https://llm.datasette.io) projects.

Plugins are activated by installing them into the same virtual environment as the application. They are deactivated by uninstalling them.

I'm interested in ways of decoupling the activation and deactivation of plugins from their installation.

This is for a few reasons. One is that I'd like to provide Docker container images that bundle many of the most popular plugins, while still allowing my users to select which plugins that are actually going to use.

Are there any good patterns for implementing this kind of thing that I could use as inspiration here?

**Comment by RonnyPfannschmidt** [comment]
Pytest uses the pytest-configure hook to register plugin objects for extra opt in behavior

The builtin junitxml plugin can be a inspection

**Comment by RonnyPfannschmidt** [comment]
Your plan might work better with a allo/deny list though

**Comment by simonw** [comment]
> Plugins are loaded/activated by explicitly calling [`PluginManager.load_setuptools_entrypoints()`](https://pluggy.readthedocs.io/en/stable/#loading-setuptools-entry-points), so they are not really automatic...

Yes, that's a really good point! Both LLM and Datasette use this pattern: https://github.com/simonw/datasette/blob/0f7192b6154edb576c41b55bd3f2a3f53e5f436a/datasette/plugins.py#L22-L27

```python
pm = pluggy.PluginManager("datasette")
pm.add_hookspecs(hookspecs)

if not hasattr(sys, "_called_from_test"):
    # Only load plugins if not running tests
    pm.load_setuptools_entrypoints("datasette")
```
I'm currently loading those at the base level of the module when it is imported, but I guess I could instead put that inside my Click command functions, which would enable me to perform some additional logic as part of loading them.

One problem there is that one of the things plugins can do is register additional Click commands, so they do need to be loaded as early as possible. https://docs.datasette.io/en/stable/plugin_hooks.html#register-commands-cli

**Comment by simonw** [comment]
Here's the implementation of that method: https://github.com/pytest-dev/pluggy/blob/e507275d33b03b7e7161b2d8c9b184939973bc91/src/pluggy/_manager.py#L345-L368

It looks simple enough that I could roll my own custom version of it, which consults some additional source of information to decide if an installed plugin should be loaded or not.

**Comment by simonw** [comment]
Also it looks like I might be able to take advantage of this "blocked" mechanism: https://github.com/pytest-dev/pluggy/blob/e507275d33b03b7e7161b2d8c9b184939973bc91/src/pluggy/_manager.py#L205-L212

**Comment by simonw** [comment]
Also just spotted this pattern in `pytest`: https://github.com/pytest-dev/pytest/blob/7008385253939271c7046f37f4008e1b7dcbe75c/src/_pytest/config/__init__.py#L1305-L1308

```python
        if not os.environ.get("PYTEST_DISABLE_PLUGIN_AUTOLOAD"):
            # Don't autoload from setuptools entry point. Only explicitly specified
            # plugins are going to be loaded.
            self.pluginmanager.load_setuptools_entrypoints("pytest11")
```

**Comment by simonw** [comment]
OK, I think I understand what I need to do here then.

If I'm going to implement an allow-list of plugins, the way to do it is to drop the `pm.load_setuptools_entrypoints("datasette")` line entirely and, instead, to loop through whatever list of plugins I have in my allowlist and `register()` them each in turn.

I can do that at the earliest point in my code that makes sense.

The one thing I'm a bit stuck on is what to do about my `register_commands()` plugins. Those need to run outside of my usual codepaths, because they affect what commands are available to my app.

I could load them based on environment variables but it's a bit ugly - I'd rather have the list of enabled plugins in a configuration file of some sort.

I guess what I need there is for my `if __name__ == "__main__"` block to do the plugin loading, before it dispatches control over to the main Click `cli()` method.

Thanks for the help everyone!
