### ISSUE TITLE
Stick docs link in the Github project title

### ISSUE THREAD

**Issue by tgoodlet** [pytest-dev/pluggy#45]
@nicoddemus @hpk42 even as a collaborator I don't seem to be able to modify the title to stick in the docs link :(

I was just thinking it might be a good way to get newcomers more quickly immersed by tempting them with a docs link at the inset ;)

Anyway let me know what you guys think!

**Comment by nicoddemus** [comment]
Just did it, please take a look at the main page of the project and let me know if was that what you meant. 👍

**Comment by nicoddemus** [comment]
Btw, perhaps we should add a small Python example to the README, along with license information?

**Comment by tgoodlet** [comment]
@nicoddemus yes good idea I made #47.
And yes this is perfect thanks!
