### ISSUE TITLE
Fix up the readme

### ISSUE THREAD

**Issue by tgoodlet** [pytest-dev/pluggy#47]
As per @nicoddemus's suggestion It'd be good to have an introductory example and a little more excitement there ;)

**Comment by hpk42** [comment]
let me randomly note here that pluggy is used successfully also by tox and by devpi-server and probably by others (i never checked).  So i suggest to not emphasize "pytest plugin system" too much but rather "pluggy: a little field-proven plugin manager" or something.

**Comment by tgoodlet** [comment]
@hpk42 good point and will do :)
