### ISSUE TITLE
[FR] Rename `load_setuptools_entrypoints` to `load_package_metadata_entrypoints()`

### ISSUE THREAD

**Issue by webknjaz** [pytest-dev/pluggy#514]
It's here https://github.com/pytest-dev/pluggy/blob/main/src/pluggy/_manager.py#L397C14-L397C24. Should go through a long deprecation period, of course.

`setuptools` is also mentioned in the docs: https://github.com/pytest-dev/pluggy/blob/3fde0aece728642652c52fb9773aa99ab31e803f/docs/index.rst?plain=1#L731-L735

**Comment by noklam** [comment]
See this:
- https://github.com/pytest-dev/pluggy/issues/440

p.s. I am not a pluggy dev

**Comment by RonnyPfannschmidt** [comment]
Closing as duplicates of #154

@noklam thanks for fetching the references
