### ISSUE TITLE
Duplicate firstresult tests?

### ISSUE THREAD

**Issue by tgoodlet** [pytest-dev/pluggy#61]
I noticed that the tests [here](https://github.com/pytest-dev/pluggy/blob/master/testing/test_method_ordering.py#L183) and [here](https://github.com/pytest-dev/pluggy/blob/master/testing/test_hookrelay.py#L63) appear to be essentially duplicates under different names?
Is there any reason I should not remove one of them?

**Comment by RonnyPfannschmidt** [comment]
interestingly its not only a duplicate, but the test is also incomplete

**Comment by nicoddemus** [comment]
Yep, `test_firstresult_definition` is indeed incomplete.
