### ISSUE TITLE
Use relative imports for test suite

### ISSUE THREAD

**Issue by tgoodlet** [pytest-dev/pluggy#63]
As per discussion in pytest-dev/pytest#2716 I want to see if we can avoid self-hosted testing of `pluggy` by using relative imports in the test suite. I think the only hurdle will be making `tox` work alongside. TravisCI shouldn't have any problems afaik.

**Comment by RonnyPfannschmidt** [comment]
well - the only way to do that would be to break the python import mechanism, as relative imports are supposed to work only within the local package tree, not across package trees

**Comment by tgoodlet** [comment]
@RonnyPfannschmidt right. 

So my thinking is for dev testing we only need to test the local `pluggy` code where some other stable version can be used as a dep by `pytest`.

Let me see if I can come up with something and we can talk :)

**Comment by nicoddemus** [comment]
It is fine to use relative imports, but that doesn't mean that the modules will be isolated in anyway: a module inside `pluggy` package that executes `from . import callers` will import the exact same module as if executing `from pluggy import callers`, which is also the same module imported from another package (say pytest) executing `import pluggy.callers`.

**Comment by RonnyPfannschmidt** [comment]
we can test a un-installed pluggy in isolation by mapping it to a new name, we cant test a installed pluggy in isolation at all - python is just broken there

**Comment by nicoddemus** [comment]
I think @RonnyPfannschmidt and I are saying the same thing, we can close this as "won't fix" because there's no practical solution for it. 😁

**Comment by tgoodlet** [comment]
@nicoddemus just hold up. I'm pretty sure I know how to make this work. If I fail I'll close it ;)

**Comment by nicoddemus** [comment]
@tgoodlet sure please go ahead! 😁

**Comment by tgoodlet** [comment]
@nicoddemus ok I take it back. You're right I'd have to hack around it with `sys.modules` which I think is doable but I'm not going to bother until it's needed.

**Comment by nicoddemus** [comment]
Thanks for trying! 👍
