### ISSUE TITLE
Document how hook call order is affected by plugin registration

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pluggy#64]
As discussed in #62, we should explicitly document how hook call order is done regarding how plugins are registered. 

From the top of my head, hooks are called in this order:

1. setuptools plugins (in arbitrary order, except those marked with `try_first` and `try_last`);
2. core plugins;

**Comment by astrojuanlu** [comment]
> setuptools plugins (in arbitrary order

I know this is an ancient issue but I don't think this fact was sufficiently documented in gh-85.
