### ISSUE TITLE
0.5.0 release!

### ISSUE THREAD

**Issue by tgoodlet** [pytest-dev/pluggy#65]
Once pytest-dev/pytest#2719 get's in we should do a new release and get the fast(er) version of `pluggy`'s core out in the wild as well as the fixes since `0.4.0`. I wasn't sure if it should be a patch or a full minor.

@hpk42 @nicoddemus @RonnyPfannschmidt I'd be glad to take on this reponsibility from now on if you all are ok with it. I will need to have access to the pypi account however.

Let me know what you guys think!

**Comment by nicoddemus** [comment]
A quick look at the changelog suggests that there are new features ("allow registering hookspecs from instances") so the next release should be `0.5.0`.

> @hpk42 @nicoddemus @RonnyPfannschmidt I'd be glad to take on this reponsibility from now on if you all are ok with it. I will need to have access to the pypi account however.

Oh definitely, you are a maintainer and should have access (it was an oversight). What's your PyPI username?

**Comment by tgoodlet** [comment]
@nicoddemus sounds good! My username is `goodboy`.
I will update the changelog as well with the recent stuff 👍

I was also going to ask, given that I'm now trying to take on the bulk of helping maintain `pluggy`, would it be possible to become part of the `pytest-dev` org or is there some other special requirement I'd need to satisfy first?

**Comment by nicoddemus** [comment]
> My username is goodboy. 

Done, let me know if you have any problems.

> I was also going to ask, given that I'm now trying to take on the bulk of helping maintain pluggy, would it be possible to become part of the pytest-dev org or is there some other special requirement I'd need to satisfy first?

Oh I was under the impression you already were on `pytest-dev`. Of course no other requirements needed, you are the main maintainer today of a vital piece of our infrastructure and your work speaks for itself, that's more than enough. 😉

**Comment by nicoddemus** [comment]
I've added you to PyPI, pytest-dev and created a `pluggy-admin` team. Let me know if anything is missing. 😉

**Comment by tgoodlet** [comment]
@nicoddemus amazing 👍 
I'll move forward with `0.5.0` shortly!

**Comment by tgoodlet** [comment]
Completeed in #67
