### ISSUE TITLE
adapting towncrier and release automation

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pluggy#66]
we should take a look for handling this here as well

**Comment by tgoodlet** [comment]
@RonnyPfannschmidt good idea.
I only looked over it briefly but seems a very nice bit of automation.
Is it ok if we bring that in after the `0.5.0` release?

**Comment by RonnyPfannschmidt** [comment]
@tgoodlet yesl, lets not be this a blocker

i want to make it much more nice for all of pytest-dev and that needs some work (im waiting for the pypi name wolf to get transferred to me)

**Comment by tgoodlet** [comment]
@RonnyPfannschmidt cool sounds good :)
