### ISSUE TITLE
regression for firstresult hook without implementation

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pluggy#68]
https://github.com/devpi/devpi/issues/458

is triggered by https://github.com/pytest-dev/pluggy/pull/58/files#diff-85f4be4e30ec3b4f3d53843b24d72141R109

@tgoodlet i beleive a test is needed for those edge behaviours

**Comment by tgoodlet** [comment]
@RonnyPfannschmidt shoot! 
Yeah I guess we need more complete testing..
I actually was able to trigger this once but could never reproduce.
I'll get a PR in stat!

**Comment by tgoodlet** [comment]
@RonnyPfannschmidt got a fix up.

Isn't it a bit odd that the `devpi` main routine is invoking 
```python
res = xom.config.hook.devpiserver_cmdline_run(xom=xom)
```
which [according to the spec](https://github.com/devpi/devpi/blob/6f29ed0d46eb101d6ef7f8889644954228080106/server/devpi_server/hookspecs.py#L15) is supposed to return an exit code?

Maybe I'm missing something but that seems like odd behaviour that all impls are called without any handling the cmdline (or maybe not returning a result when they're supposed to)?
