### ISSUE TITLE
Error: warnings has no attribute DeprecationWarning

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pluggy#75]
While testing `pluggy` off the branch from #72, I came across this error:

```
        if '__multicall__' in hookimpl.argnames:
            warnings.warn(
                "Support for __multicall__ is now deprecated and will be"
                "removed in an upcoming release.",
>               warnings.DeprecationWarning
            )
E           AttributeError: module 'warnings' has no attribute 'DeprecationWarning'
```

https://github.com/pytest-dev/pluggy/blob/557cd3f0245347c1cd359c6deb4b25cde944e98a/pluggy/__init__.py#L656-L661

And indeed `warnings` module doesn't have a `DeprecationWarning`.

We should add a test to catch this warnings (and any others we might have).

**Comment by tgoodlet** [comment]
@nicoddemus wow yeah not sure how that slipped through.
Looks like `DeprecationWarning` is a built-in. Does it exist in py26?

**Comment by tgoodlet** [comment]
@nicoddemus you ok if I just fix this in #72 or should I do a separate PR?

**Comment by nicoddemus** [comment]
I'm running pytest's test suite right now and fixing the `__multicall__` usages to see if there are other problems related to pluggy still, but after that I will push a PR fixing this particular issue. 😉

**Comment by nicoddemus** [comment]
> you ok if I just fix this in #72 or should I do a separate PR?

You replied a few seconds before me hehehe.

If you want to take a stab please go ahead, I just think we should do a separate PR because we also need to include a proper test for it.

**Comment by tgoodlet** [comment]
@nicoddemus ok great I'm cool with you taking it ;)

**Comment by nicoddemus** [comment]
OK sounds good.
