### ISSUE TITLE
Execute some build environments using latest pytest and/or master

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pluggy#76]
As discussed in pytest-dev/pytest#2730

**Comment by tgoodlet** [comment]
It might be good to do both?

**Comment by nicoddemus** [comment]
Agreed, that's what I meant actually (updated the title).

**Comment by RonnyPfannschmidt** [comment]
i think we should have a cronjob for master/features of pytest and also have a cronjob for pytest to test with pluggy master

**Comment by nicoddemus** [comment]
Agreed. Could you please create a similar issue in pytest Ronny?
