### ISSUE TITLE
0.5.2 release

### ISSUE THREAD

**Issue by tgoodlet** [pytest-dev/pluggy#82]
I just got an email that `0.5.1` is being shipped on NetBSD.
We need to get `0.5.2` out soon!

Things blocking:
- #79
- pytest-dev/pytest#2737

I think it should be pretty quick to get these complete :)

**Comment by nicoddemus** [comment]
Sorry for the silence in the last few days, a lot of social appointments have kept me away from OS work. 😁 

I will pick those up later today, but I don't think they are blocking `0.5.2` because they deal with infrastructure only.

**Comment by tgoodlet** [comment]
@nicoddemus alright cool I'll put up a PR for this shortly then.

**Comment by tgoodlet** [comment]
Closed via #83.
Package is now [live](https://pypi.org/project/pluggy/).
