### ISSUE TITLE
Turn _MultiCall into a function

### ISSUE THREAD

**Issue by tgoodlet** [pytest-dev/pluggy#84]
Now that #23 has landed it seems fit that we evaluate the [`_MultiCall`](https://github.com/pytest-dev/pluggy/blob/master/pluggy/callers.py#L58) type.

Afaict this class contains a single method `execute()` other then `__init__` (and `__repr__` but who uses it?) and that method was only necessary for the original recursive implementation.

I'm wondering can we simplify the whole thing into a simple function? 

Reasons for:
- `_MultiCall` keeps no state since it's execute method [is always called directly after instantiation](https://github.com/pytest-dev/pluggy/blob/master/pluggy/__init__.py#L233)
- `_MultiCall` instances are never *reused*
- having a function is less code, faster and arguably easier to cythonize

**Comment by RonnyPfannschmidt** [comment]
well - multicall instances are used in the sense tat we currently pick multicall vs legacy multicall

if we alter the hook calller invocation pattern then we can surely turn the actual invocation into only a function call

**Comment by nicoddemus** [comment]
I'm 👍 on the idea as well.

**Comment by tgoodlet** [comment]
@nicoddemus right so this will be most easily pushed through once #59 is fully in which I'd expect won't be until the next minor or even major release.

>if we alter the hook calller invocation pattern

We can also just have the `_LegacyMultiCall` calls to `__init__` and `execute` wrapped inside a function which is mapped in the legacy case yah?

**Comment by RonnyPfannschmidt** [comment]
@tgoodlet instantiate and initial execute can be wrapped into a function in both cases i think
