### ISSUE TITLE
trigger a deprecationwarning for Result.excinfo

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pluggy#86]
https://github.com/pytest-dev/pluggy/blob/1037dc9615fda1bece07169fbd3c61956ef01b26/pluggy/callers.py#L32-L34

we kept the code for pytest, but we should at least deprecate it and remove the use in future

**Comment by tgoodlet** [comment]
@RonnyPfannschmidt works for me.

**Comment by tgoodlet** [comment]
@RonnyPfannschmidt wait so we don't want to allow for public access at all?
Is the idea that users can catch the underlying exception instead from `get_result()`?

**Comment by RonnyPfannschmidt** [comment]
correct

**Comment by RonnyPfannschmidt** [comment]
@tgoodlet thanks for the reminder, i still haven't come up with a reasonable failure indication system, i believe this will require a little collaborative brainstorming to generate ideas

**Comment by nicoddemus** [comment]
What was the rationale for not exposing the exception object again?

**Comment by RonnyPfannschmidt** [comment]
closing this one as it will disappear with the deprecation/removal of result objects in #260
