### ISSUE TITLE
GitHub release of 0.5.2

### ISSUE THREAD

**Issue by TBK** [pytest-dev/pluggy#93]
Hi, would it be possible to make a release of 0.5.2 here on GitHub?

**Comment by tgoodlet** [comment]
Hey @TBK the version on [warehouse](https://pypi.org/project/pluggy/) and [pypi](https://pypi.python.org/pypi/pluggy) is 0.5.2 I believe. 
Is this what you mean -> [Github Release](https://help.github.com/articles/creating-releases/)?

**Comment by tgoodlet** [comment]
@TBK ahh I see what you mean. I hadn't pushed the `0.5.2` tag.
Just did that. Let me know if it's working for you.

**Comment by TBK** [comment]
@tgoodlet Thanks, it works beautifully 👍

**Comment by tgoodlet** [comment]
@TBK no prob!
Just curious, what are you doing that requires the release on GH?

**Comment by TBK** [comment]
Alpine Linux packaging :)
